apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: my-container
        image: varsha0822/frontend-app:1.0  # Change to the correct image name
        ports:
        - containerPort: 3000  # Update to your preferred port if needed
